use cdm_plugin_interface::{Delta, OutputFile, Schema, Utils, JSON};

/// Generates migration files from schema changes
pub fn migrate(
    current_schema: Schema,
    deltas: Vec<Delta>,
    config: JSON,
    utils: &Utils,
) -> Vec<OutputFile> {
    let mut files = Vec::new();

    if deltas.is_empty() {
        return files;
    }

    // TODO: Implement your migration logic here
    // Example: Generate migration files based on deltas

    let mut migration_content = String::new();
    migration_content.push_str("-- Migration generated by CDM\n\n");

    for delta in &deltas {
        match delta {
            Delta::ModelAdded { name, after } => {
                migration_content.push_str(&format!("-- Add model: {}\n", name));
                // TODO: Generate CREATE TABLE or equivalent
            }
            Delta::ModelRemoved { name, before } => {
                migration_content.push_str(&format!("-- Remove model: {}\n", name));
                // TODO: Generate DROP TABLE or equivalent
            }
            Delta::ModelRenamed {
                old_name,
                new_name,
                id,
                ..
            } => {
                migration_content.push_str(&format!(
                    "-- Rename model: {} -> {} (ID: {:?})\n",
                    old_name, new_name, id
                ));
                // TODO: Generate RENAME TABLE or equivalent
            }
            Delta::FieldAdded { model, field, after } => {
                migration_content.push_str(&format!(
                    "-- Add field {}.{}\n",
                    model, field
                ));
                // TODO: Generate ALTER TABLE ADD COLUMN or equivalent
            }
            Delta::FieldRemoved { model, field, before } => {
                migration_content.push_str(&format!(
                    "-- Remove field {}.{}\n",
                    model, field
                ));
                // TODO: Generate ALTER TABLE DROP COLUMN or equivalent
            }
            Delta::FieldRenamed {
                model,
                old_name,
                new_name,
                id,
                ..
            } => {
                migration_content.push_str(&format!(
                    "-- Rename field {}.{} -> {} (ID: {:?})\n",
                    model, old_name, new_name, id
                ));
                // TODO: Generate ALTER TABLE RENAME COLUMN or equivalent
            }
            Delta::FieldTypeChanged {
                model,
                field,
                before,
                after,
            } => {
                migration_content.push_str(&format!(
                    "-- Change type of {}.{}\n",
                    model, field
                ));
                // TODO: Generate ALTER TABLE ALTER COLUMN or equivalent
            }
            Delta::FieldOptionalityChanged {
                model,
                field,
                before,
                after,
            } => {
                migration_content.push_str(&format!(
                    "-- Change optionality of {}.{}: {} -> {}\n",
                    model, field, before, after
                ));
                // TODO: Handle NULL/NOT NULL constraints
            }
            Delta::FieldDefaultChanged {
                model,
                field,
                before,
                after,
            } => {
                migration_content.push_str(&format!(
                    "-- Change default of {}.{}\n",
                    model, field
                ));
                // TODO: Generate ALTER TABLE ALTER COLUMN SET DEFAULT or equivalent
            }
            Delta::TypeAliasAdded { name, after } => {
                migration_content.push_str(&format!("-- Add type alias: {}\n", name));
                // Type aliases may not generate migration code depending on your target
            }
            Delta::TypeAliasRemoved { name, before } => {
                migration_content.push_str(&format!("-- Remove type alias: {}\n", name));
            }
            Delta::TypeAliasRenamed {
                old_name,
                new_name,
                id,
                ..
            } => {
                migration_content.push_str(&format!(
                    "-- Rename type alias: {} -> {} (ID: {:?})\n",
                    old_name, new_name, id
                ));
            }
            Delta::TypeAliasTypeChanged { name, before, after } => {
                migration_content.push_str(&format!(
                    "-- Change type alias: {}\n",
                    name
                ));
            }
            Delta::InheritanceAdded { model, parent } => {
                migration_content.push_str(&format!(
                    "-- Add inheritance: {} extends {}\n",
                    model, parent
                ));
            }
            Delta::InheritanceRemoved { model, parent } => {
                migration_content.push_str(&format!(
                    "-- Remove inheritance: {} extends {}\n",
                    model, parent
                ));
            }
            Delta::GlobalConfigChanged { before, after } => {
                migration_content.push_str("-- Global config changed\n");
            }
            Delta::ModelConfigChanged { model, before, after } => {
                migration_content.push_str(&format!(
                    "-- Model config changed: {}\n",
                    model
                ));
            }
            Delta::FieldConfigChanged {
                model,
                field,
                before,
                after,
            } => {
                migration_content.push_str(&format!(
                    "-- Field config changed: {}.{}\n",
                    model, field
                ));
            }
        }
    }

    // Create migration file
    files.push(OutputFile {
        path: "migration.sql".to_string(),
        content: migration_content,
    });

    files
}

#[cfg(test)]
mod tests {
    use super::*;
    use cdm_plugin_interface::{FieldDefinition, ModelDefinition, TypeExpression};
    use std::collections::HashMap;

    #[test]
    fn test_migrate_empty() {
        let schema = Schema {
            type_aliases: HashMap::new(),
            models: HashMap::new(),
        };

        let config = serde_json::json!({});
        let utils = Utils;

        let files = migrate(schema, vec![], config, &utils);
        assert!(files.is_empty());
    }

    #[test]
    fn test_migrate_with_deltas() {
        let schema = Schema {
            type_aliases: HashMap::new(),
            models: HashMap::new(),
        };

        let deltas = vec![Delta::ModelAdded {
            name: "User".to_string(),
            after: ModelDefinition {
                name: "User".to_string(),
                entity_id: Some(1),
                parents: vec![],
                fields: vec![],
                config: serde_json::json!({}),
            },
        }];

        let config = serde_json::json!({});
        let utils = Utils;

        let files = migrate(schema, deltas, config, &utils);
        assert_eq!(files.len(), 1);
        assert!(files[0].content.contains("Add model: User"));
    }
}
