/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 111
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 65
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 14
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 24
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_comment = 2,
  anon_sym_AT = 3,
  anon_sym_from = 4,
  anon_sym_git_COLON = 5,
  sym_git_url = 6,
  sym_plugin_path = 7,
  anon_sym_ATextends = 8,
  sym_path = 9,
  anon_sym_DASH = 10,
  anon_sym_COLON = 11,
  anon_sym_extends = 12,
  anon_sym_COMMA = 13,
  anon_sym_LBRACE = 14,
  anon_sym_RBRACE = 15,
  anon_sym_QMARK = 16,
  anon_sym_EQ = 17,
  anon_sym_PIPE = 18,
  anon_sym_LBRACK = 19,
  anon_sym_RBRACK = 20,
  anon_sym_DQUOTE = 21,
  sym_string_content = 22,
  sym_escape_sequence = 23,
  sym_number_literal = 24,
  anon_sym_true = 25,
  anon_sym_false = 26,
  sym_source_file = 27,
  sym__definition = 28,
  sym_plugin_import = 29,
  sym_plugin_source = 30,
  sym_git_reference = 31,
  sym_extends_directive = 32,
  sym_model_removal = 33,
  sym_type_alias = 34,
  sym_model_definition = 35,
  sym_extends_clause = 36,
  sym_model_body = 37,
  sym__model_member = 38,
  sym_field_removal = 39,
  sym_field_override = 40,
  sym_field_definition = 41,
  sym__default_value = 42,
  sym__type_expression = 43,
  sym_union_type = 44,
  sym__union_member = 45,
  sym_type_identifier = 46,
  sym_array_type = 47,
  sym__value = 48,
  sym_array_literal = 49,
  sym_object_literal = 50,
  sym_object_entry = 51,
  sym_plugin_block = 52,
  sym_plugin_config = 53,
  sym_string_literal = 54,
  sym_boolean_literal = 55,
  aux_sym_source_file_repeat1 = 56,
  aux_sym_source_file_repeat2 = 57,
  aux_sym_extends_clause_repeat1 = 58,
  aux_sym_model_body_repeat1 = 59,
  aux_sym_union_type_repeat1 = 60,
  aux_sym_array_literal_repeat1 = 61,
  aux_sym_object_literal_repeat1 = 62,
  aux_sym_plugin_block_repeat1 = 63,
  aux_sym_string_literal_repeat1 = 64,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [anon_sym_AT] = "@",
  [anon_sym_from] = "from",
  [anon_sym_git_COLON] = "git:",
  [sym_git_url] = "git_url",
  [sym_plugin_path] = "plugin_path",
  [anon_sym_ATextends] = "@extends",
  [sym_path] = "path",
  [anon_sym_DASH] = "-",
  [anon_sym_COLON] = ":",
  [anon_sym_extends] = "extends",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_QMARK] = "\?",
  [anon_sym_EQ] = "=",
  [anon_sym_PIPE] = "|",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DQUOTE] = "\"",
  [sym_string_content] = "string_content",
  [sym_escape_sequence] = "escape_sequence",
  [sym_number_literal] = "number_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_plugin_import] = "plugin_import",
  [sym_plugin_source] = "plugin_source",
  [sym_git_reference] = "git_reference",
  [sym_extends_directive] = "extends_directive",
  [sym_model_removal] = "model_removal",
  [sym_type_alias] = "type_alias",
  [sym_model_definition] = "model_definition",
  [sym_extends_clause] = "extends_clause",
  [sym_model_body] = "model_body",
  [sym__model_member] = "_model_member",
  [sym_field_removal] = "field_removal",
  [sym_field_override] = "field_override",
  [sym_field_definition] = "field_definition",
  [sym__default_value] = "_default_value",
  [sym__type_expression] = "_type_expression",
  [sym_union_type] = "union_type",
  [sym__union_member] = "_union_member",
  [sym_type_identifier] = "type_identifier",
  [sym_array_type] = "array_type",
  [sym__value] = "_value",
  [sym_array_literal] = "array_literal",
  [sym_object_literal] = "object_literal",
  [sym_object_entry] = "object_entry",
  [sym_plugin_block] = "plugin_block",
  [sym_plugin_config] = "plugin_config",
  [sym_string_literal] = "string_literal",
  [sym_boolean_literal] = "boolean_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_extends_clause_repeat1] = "extends_clause_repeat1",
  [aux_sym_model_body_repeat1] = "model_body_repeat1",
  [aux_sym_union_type_repeat1] = "union_type_repeat1",
  [aux_sym_array_literal_repeat1] = "array_literal_repeat1",
  [aux_sym_object_literal_repeat1] = "object_literal_repeat1",
  [aux_sym_plugin_block_repeat1] = "plugin_block_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_git_COLON] = anon_sym_git_COLON,
  [sym_git_url] = sym_git_url,
  [sym_plugin_path] = sym_plugin_path,
  [anon_sym_ATextends] = anon_sym_ATextends,
  [sym_path] = sym_path,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_extends] = anon_sym_extends,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_string_content] = sym_string_content,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_number_literal] = sym_number_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_plugin_import] = sym_plugin_import,
  [sym_plugin_source] = sym_plugin_source,
  [sym_git_reference] = sym_git_reference,
  [sym_extends_directive] = sym_extends_directive,
  [sym_model_removal] = sym_model_removal,
  [sym_type_alias] = sym_type_alias,
  [sym_model_definition] = sym_model_definition,
  [sym_extends_clause] = sym_extends_clause,
  [sym_model_body] = sym_model_body,
  [sym__model_member] = sym__model_member,
  [sym_field_removal] = sym_field_removal,
  [sym_field_override] = sym_field_override,
  [sym_field_definition] = sym_field_definition,
  [sym__default_value] = sym__default_value,
  [sym__type_expression] = sym__type_expression,
  [sym_union_type] = sym_union_type,
  [sym__union_member] = sym__union_member,
  [sym_type_identifier] = sym_type_identifier,
  [sym_array_type] = sym_array_type,
  [sym__value] = sym__value,
  [sym_array_literal] = sym_array_literal,
  [sym_object_literal] = sym_object_literal,
  [sym_object_entry] = sym_object_entry,
  [sym_plugin_block] = sym_plugin_block,
  [sym_plugin_config] = sym_plugin_config,
  [sym_string_literal] = sym_string_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_extends_clause_repeat1] = aux_sym_extends_clause_repeat1,
  [aux_sym_model_body_repeat1] = aux_sym_model_body_repeat1,
  [aux_sym_union_type_repeat1] = aux_sym_union_type_repeat1,
  [aux_sym_array_literal_repeat1] = aux_sym_array_literal_repeat1,
  [aux_sym_object_literal_repeat1] = aux_sym_object_literal_repeat1,
  [aux_sym_plugin_block_repeat1] = aux_sym_plugin_block_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_git_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_git_url] = {
    .visible = true,
    .named = true,
  },
  [sym_plugin_path] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ATextends] = {
    .visible = true,
    .named = false,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_extends] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_string_content] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_plugin_import] = {
    .visible = true,
    .named = true,
  },
  [sym_plugin_source] = {
    .visible = true,
    .named = true,
  },
  [sym_git_reference] = {
    .visible = true,
    .named = true,
  },
  [sym_extends_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_model_removal] = {
    .visible = true,
    .named = true,
  },
  [sym_type_alias] = {
    .visible = true,
    .named = true,
  },
  [sym_model_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_extends_clause] = {
    .visible = true,
    .named = true,
  },
  [sym_model_body] = {
    .visible = true,
    .named = true,
  },
  [sym__model_member] = {
    .visible = false,
    .named = true,
  },
  [sym_field_removal] = {
    .visible = true,
    .named = true,
  },
  [sym_field_override] = {
    .visible = true,
    .named = true,
  },
  [sym_field_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__default_value] = {
    .visible = false,
    .named = true,
  },
  [sym__type_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_union_type] = {
    .visible = true,
    .named = true,
  },
  [sym__union_member] = {
    .visible = false,
    .named = true,
  },
  [sym_type_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym__value] = {
    .visible = false,
    .named = true,
  },
  [sym_array_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_object_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_object_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_plugin_block] = {
    .visible = true,
    .named = true,
  },
  [sym_plugin_config] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_extends_clause_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_model_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_union_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_plugin_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_config = 2,
  field_default = 3,
  field_extends = 4,
  field_key = 5,
  field_name = 6,
  field_optional = 7,
  field_parent = 8,
  field_path = 9,
  field_plugins = 10,
  field_source = 11,
  field_type = 12,
  field_url = 13,
  field_value = 14,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_config] = "config",
  [field_default] = "default",
  [field_extends] = "extends",
  [field_key] = "key",
  [field_name] = "name",
  [field_optional] = "optional",
  [field_parent] = "parent",
  [field_path] = "path",
  [field_plugins] = "plugins",
  [field_source] = "source",
  [field_type] = "type",
  [field_url] = "url",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 1},
  [7] = {.index = 9, .length = 1},
  [8] = {.index = 10, .length = 3},
  [9] = {.index = 13, .length = 2},
  [10] = {.index = 15, .length = 3},
  [11] = {.index = 18, .length = 2},
  [12] = {.index = 20, .length = 2},
  [13] = {.index = 22, .length = 2},
  [14] = {.index = 24, .length = 1},
  [15] = {.index = 25, .length = 3},
  [16] = {.index = 28, .length = 2},
  [17] = {.index = 30, .length = 2},
  [18] = {.index = 32, .length = 3},
  [19] = {.index = 35, .length = 3},
  [20] = {.index = 38, .length = 4},
  [21] = {.index = 42, .length = 4},
  [22] = {.index = 46, .length = 4},
  [23] = {.index = 50, .length = 5},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
  [1] =
    {field_path, 1},
  [2] =
    {field_body, 1},
    {field_name, 0},
  [4] =
    {field_config, 2},
    {field_name, 1},
  [6] =
    {field_name, 0},
    {field_type, 2},
  [8] =
    {field_parent, 1},
  [9] =
    {field_name, 0},
  [10] =
    {field_body, 2},
    {field_extends, 1},
    {field_name, 0},
  [13] =
    {field_name, 1},
    {field_source, 3},
  [15] =
    {field_name, 0},
    {field_plugins, 3},
    {field_type, 2},
  [18] =
    {field_parent, 1},
    {field_parent, 2, .inherited = true},
  [20] =
    {field_name, 0},
    {field_optional, 1},
  [22] =
    {field_name, 0},
    {field_plugins, 1},
  [24] =
    {field_url, 1},
  [25] =
    {field_config, 4},
    {field_name, 1},
    {field_source, 3},
  [28] =
    {field_parent, 0, .inherited = true},
    {field_parent, 1, .inherited = true},
  [30] =
    {field_key, 0},
    {field_value, 2},
  [32] =
    {field_name, 0},
    {field_optional, 1},
    {field_type, 3},
  [35] =
    {field_default, 4},
    {field_name, 0},
    {field_type, 2},
  [38] =
    {field_name, 0},
    {field_optional, 1},
    {field_plugins, 4},
    {field_type, 3},
  [42] =
    {field_default, 4},
    {field_name, 0},
    {field_plugins, 5},
    {field_type, 2},
  [46] =
    {field_default, 5},
    {field_name, 0},
    {field_optional, 1},
    {field_type, 3},
  [50] =
    {field_default, 5},
    {field_name, 0},
    {field_optional, 1},
    {field_plugins, 6},
    {field_type, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '"', 53,
        ',', 45,
        '-', 43,
        '.', 4,
        '/', 6,
        ':', 44,
        '=', 49,
        '?', 48,
        '@', 34,
        '[', 51,
        '\\', 17,
        ']', 52,
        'g', 62,
        '{', 46,
        '|', 50,
        '}', 47,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 53,
        '-', 19,
        '/', 6,
        '@', 33,
        '[', 51,
        ']', 52,
        '{', 46,
        '}', 47,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(53);
      if (lookahead == '/') ADVANCE(56);
      if (lookahead == '\\') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(4);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == 'g') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(5);
      if (lookahead == '/') ADVANCE(25);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(25);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(32);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 8:
      if (lookahead == '/') ADVANCE(36);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(37);
      END_STATE();
    case 9:
      if (lookahead == ':') ADVANCE(35);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(39);
      END_STATE();
    case 15:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 17:
      ADVANCE_MAP(
        'u', 24,
        '"', 58,
        '/', 58,
        '\\', 58,
        'b', 58,
        'f', 58,
        'n', 58,
        'r', 58,
        't', 58,
      );
      END_STATE();
    case 18:
      if (lookahead == 'x') ADVANCE(15);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(58);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(38);
      END_STATE();
    case 26:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        '"', 53,
        ',', 45,
        '-', 43,
        '.', 4,
        '/', 6,
        ':', 44,
        '=', 49,
        '?', 48,
        '@', 34,
        '[', 51,
        ']', 52,
        'g', 62,
        '{', 46,
        '|', 50,
        '}', 47,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 27:
      if (eof) ADVANCE(29);
      if (lookahead == '"') ADVANCE(53);
      if (lookahead == '-') ADVANCE(42);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == ':') ADVANCE(44);
      if (lookahead == '@') ADVANCE(34);
      if (lookahead == '{') ADVANCE(46);
      if (lookahead == '}') ADVANCE(47);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(27);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 28:
      if (eof) ADVANCE(29);
      ADVANCE_MAP(
        ',', 45,
        '-', 42,
        '/', 6,
        ':', 44,
        '=', 49,
        '?', 48,
        '@', 33,
        '[', 51,
        ']', 52,
        '{', 46,
        '|', 50,
        '}', 47,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_AT);
      if (lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_git_COLON);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_git_url);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_git_url);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_plugin_path);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_ATextends);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_path);
      if (lookahead == '/') ADVANCE(30);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_path);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '/') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(57);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead == '/') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_string_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 't') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'x') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(5);
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 6:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 9:
      if (lookahead == 's') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'm') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(17);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 16:
      if (lookahead == 'd') ADVANCE(18);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 18:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_extends);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 27},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 28},
  [6] = {.lex_state = 28},
  [7] = {.lex_state = 28},
  [8] = {.lex_state = 28},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 28},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 28},
  [15] = {.lex_state = 28},
  [16] = {.lex_state = 28},
  [17] = {.lex_state = 28},
  [18] = {.lex_state = 28},
  [19] = {.lex_state = 28},
  [20] = {.lex_state = 28},
  [21] = {.lex_state = 28},
  [22] = {.lex_state = 28},
  [23] = {.lex_state = 27},
  [24] = {.lex_state = 27},
  [25] = {.lex_state = 28},
  [26] = {.lex_state = 28},
  [27] = {.lex_state = 27},
  [28] = {.lex_state = 27},
  [29] = {.lex_state = 28},
  [30] = {.lex_state = 28},
  [31] = {.lex_state = 28},
  [32] = {.lex_state = 27},
  [33] = {.lex_state = 27},
  [34] = {.lex_state = 28},
  [35] = {.lex_state = 28},
  [36] = {.lex_state = 27},
  [37] = {.lex_state = 28},
  [38] = {.lex_state = 28},
  [39] = {.lex_state = 28},
  [40] = {.lex_state = 28},
  [41] = {.lex_state = 28},
  [42] = {.lex_state = 28},
  [43] = {.lex_state = 28},
  [44] = {.lex_state = 28},
  [45] = {.lex_state = 28},
  [46] = {.lex_state = 28},
  [47] = {.lex_state = 27},
  [48] = {.lex_state = 28},
  [49] = {.lex_state = 28},
  [50] = {.lex_state = 27},
  [51] = {.lex_state = 28},
  [52] = {.lex_state = 28},
  [53] = {.lex_state = 28},
  [54] = {.lex_state = 27},
  [55] = {.lex_state = 27},
  [56] = {.lex_state = 28},
  [57] = {.lex_state = 27},
  [58] = {.lex_state = 27},
  [59] = {.lex_state = 28},
  [60] = {.lex_state = 28},
  [61] = {.lex_state = 28},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 28},
  [65] = {.lex_state = 28},
  [66] = {.lex_state = 3},
  [67] = {.lex_state = 28},
  [68] = {.lex_state = 2},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 28},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 27},
  [74] = {.lex_state = 28},
  [75] = {.lex_state = 28},
  [76] = {.lex_state = 28},
  [77] = {.lex_state = 28},
  [78] = {.lex_state = 27},
  [79] = {.lex_state = 27},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 27},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 27},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 27},
  [92] = {.lex_state = 27},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 7},
  [102] = {.lex_state = 27},
  [103] = {.lex_state = 27},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 27},
  [106] = {.lex_state = 27},
  [107] = {.lex_state = 27},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 27},
  [110] = {.lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_git_COLON] = ACTIONS(1),
    [sym_plugin_path] = ACTIONS(1),
    [anon_sym_ATextends] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_extends] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(104),
    [sym__definition] = STATE(24),
    [sym_plugin_import] = STATE(6),
    [sym_extends_directive] = STATE(7),
    [sym_model_removal] = STATE(24),
    [sym_type_alias] = STATE(24),
    [sym_model_definition] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_source_file_repeat2] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_identifier] = ACTIONS(7),
    [sym_comment] = ACTIONS(3),
    [anon_sym_AT] = ACTIONS(9),
    [anon_sym_ATextends] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_RBRACK,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_number_literal,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(85), 5,
      sym__value,
      sym_array_literal,
      sym_object_literal,
      sym_string_literal,
      sym_boolean_literal,
  [30] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(27), 1,
      anon_sym_RBRACK,
    ACTIONS(29), 1,
      sym_number_literal,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(96), 5,
      sym__value,
      sym_array_literal,
      sym_object_literal,
      sym_string_literal,
      sym_boolean_literal,
  [60] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      sym_number_literal,
    ACTIONS(31), 1,
      anon_sym_RBRACK,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(96), 5,
      sym__value,
      sym_array_literal,
      sym_object_literal,
      sym_string_literal,
      sym_boolean_literal,
  [90] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    ACTIONS(35), 1,
      anon_sym_AT,
    STATE(46), 2,
      sym_plugin_import,
      aux_sym_source_file_repeat1,
    STATE(23), 5,
      sym__definition,
      sym_model_removal,
      sym_type_alias,
      sym_model_definition,
      aux_sym_source_file_repeat2,
  [117] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(35), 1,
      anon_sym_AT,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    STATE(46), 2,
      sym_plugin_import,
      aux_sym_source_file_repeat1,
    STATE(33), 5,
      sym__definition,
      sym_model_removal,
      sym_type_alias,
      sym_model_definition,
      aux_sym_source_file_repeat2,
  [144] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(35), 1,
      anon_sym_AT,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    STATE(5), 2,
      sym_plugin_import,
      aux_sym_source_file_repeat1,
    STATE(33), 5,
      sym__definition,
      sym_model_removal,
      sym_type_alias,
      sym_model_definition,
      aux_sym_source_file_repeat2,
  [171] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(39), 11,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      sym_identifier,
  [188] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(41), 1,
      sym_number_literal,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(94), 5,
      sym__value,
      sym_array_literal,
      sym_object_literal,
      sym_string_literal,
      sym_boolean_literal,
  [215] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(43), 1,
      sym_number_literal,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(45), 5,
      sym__default_value,
      sym_array_literal,
      sym_object_literal,
      sym_string_literal,
      sym_boolean_literal,
  [242] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      sym_number_literal,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(48), 5,
      sym__default_value,
      sym_array_literal,
      sym_object_literal,
      sym_string_literal,
      sym_boolean_literal,
  [269] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(47), 11,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_PIPE,
      anon_sym_RBRACK,
      sym_identifier,
  [286] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(29), 1,
      sym_number_literal,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(96), 5,
      sym__value,
      sym_array_literal,
      sym_object_literal,
      sym_string_literal,
      sym_boolean_literal,
  [313] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(52), 1,
      anon_sym_AT,
    ACTIONS(55), 1,
      anon_sym_DASH,
    ACTIONS(58), 1,
      anon_sym_RBRACE,
    STATE(14), 6,
      sym__model_member,
      sym_field_removal,
      sym_field_override,
      sym_field_definition,
      sym_plugin_config,
      aux_sym_model_body_repeat1,
  [337] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      sym_identifier,
    ACTIONS(62), 1,
      anon_sym_AT,
    ACTIONS(64), 1,
      anon_sym_DASH,
    ACTIONS(66), 1,
      anon_sym_RBRACE,
    STATE(14), 6,
      sym__model_member,
      sym_field_removal,
      sym_field_override,
      sym_field_definition,
      sym_plugin_config,
      aux_sym_model_body_repeat1,
  [361] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(60), 1,
      sym_identifier,
    ACTIONS(62), 1,
      anon_sym_AT,
    ACTIONS(64), 1,
      anon_sym_DASH,
    ACTIONS(68), 1,
      anon_sym_RBRACE,
    STATE(15), 6,
      sym__model_member,
      sym_field_removal,
      sym_field_override,
      sym_field_definition,
      sym_plugin_config,
      aux_sym_model_body_repeat1,
  [385] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_PIPE,
    STATE(19), 1,
      aux_sym_union_type_repeat1,
    ACTIONS(70), 7,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      sym_identifier,
  [404] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_LBRACK,
    ACTIONS(74), 8,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_PIPE,
      sym_identifier,
  [421] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_PIPE,
    STATE(19), 1,
      aux_sym_union_type_repeat1,
    ACTIONS(78), 7,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      sym_identifier,
  [440] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(83), 9,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_PIPE,
      anon_sym_LBRACK,
      sym_identifier,
  [455] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_PIPE,
    ACTIONS(76), 1,
      anon_sym_LBRACK,
    ACTIONS(85), 7,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      sym_identifier,
  [474] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_PIPE,
    ACTIONS(85), 7,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      sym_identifier,
  [490] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    STATE(36), 5,
      sym__definition,
      sym_model_removal,
      sym_type_alias,
      sym_model_definition,
      aux_sym_source_file_repeat2,
  [510] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    STATE(36), 5,
      sym__definition,
      sym_model_removal,
      sym_type_alias,
      sym_model_definition,
      aux_sym_source_file_repeat2,
  [530] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(91), 1,
      anon_sym_COLON,
    ACTIONS(93), 1,
      anon_sym_LBRACE,
    ACTIONS(95), 1,
      anon_sym_QMARK,
    STATE(76), 1,
      sym_plugin_block,
    ACTIONS(89), 4,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_RBRACE,
      sym_identifier,
  [552] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(97), 8,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      sym_identifier,
  [566] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(21), 1,
      sym_type_identifier,
    STATE(22), 1,
      sym_array_type,
    STATE(57), 2,
      sym__type_expression,
      sym_union_type,
    STATE(95), 2,
      sym__union_member,
      sym_string_literal,
  [590] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(21), 1,
      sym_type_identifier,
    STATE(22), 1,
      sym_array_type,
    STATE(41), 2,
      sym__type_expression,
      sym_union_type,
    STATE(95), 2,
      sym__union_member,
      sym_string_literal,
  [614] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(101), 8,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      sym_identifier,
  [628] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 8,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_PIPE,
      sym_identifier,
  [642] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(103), 8,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_PIPE,
      sym_identifier,
  [656] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(21), 1,
      sym_type_identifier,
    STATE(22), 1,
      sym_array_type,
    STATE(39), 2,
      sym__type_expression,
      sym_union_type,
    STATE(95), 2,
      sym__union_member,
      sym_string_literal,
  [680] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_identifier,
    ACTIONS(13), 1,
      anon_sym_DASH,
    ACTIONS(33), 1,
      ts_builtin_sym_end,
    STATE(36), 5,
      sym__definition,
      sym_model_removal,
      sym_type_alias,
      sym_model_definition,
      aux_sym_source_file_repeat2,
  [700] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(105), 8,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      sym_identifier,
  [714] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 8,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      sym_identifier,
  [728] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(109), 1,
      ts_builtin_sym_end,
    ACTIONS(111), 1,
      sym_identifier,
    ACTIONS(114), 1,
      anon_sym_DASH,
    STATE(36), 5,
      sym__definition,
      sym_model_removal,
      sym_type_alias,
      sym_model_definition,
      aux_sym_source_file_repeat2,
  [748] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    ACTIONS(119), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_from,
    STATE(67), 1,
      sym_object_literal,
    ACTIONS(117), 3,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
  [769] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(123), 7,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      sym_identifier,
  [782] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LBRACE,
    ACTIONS(127), 1,
      anon_sym_EQ,
    STATE(60), 1,
      sym_plugin_block,
    ACTIONS(125), 4,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_RBRACE,
      sym_identifier,
  [801] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(129), 7,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      sym_identifier,
  [814] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LBRACE,
    ACTIONS(133), 1,
      anon_sym_EQ,
    STATE(71), 1,
      sym_plugin_block,
    ACTIONS(131), 4,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_RBRACE,
      sym_identifier,
  [833] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(135), 7,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      sym_identifier,
  [846] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(137), 7,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      sym_identifier,
  [859] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(139), 7,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      sym_identifier,
  [872] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LBRACE,
    STATE(75), 1,
      sym_plugin_block,
    ACTIONS(141), 4,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_RBRACE,
      sym_identifier,
  [888] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(145), 1,
      anon_sym_AT,
    STATE(46), 2,
      sym_plugin_import,
      aux_sym_source_file_repeat1,
    ACTIONS(143), 3,
      ts_builtin_sym_end,
      anon_sym_DASH,
      sym_identifier,
  [904] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(99), 1,
      sym_identifier,
    STATE(18), 1,
      sym_type_identifier,
    STATE(30), 3,
      sym__union_member,
      sym_array_type,
      sym_string_literal,
  [922] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LBRACE,
    STATE(77), 1,
      sym_plugin_block,
    ACTIONS(148), 4,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_RBRACE,
      sym_identifier,
  [938] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(61), 1,
      sym_object_literal,
    ACTIONS(150), 4,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      sym_identifier,
  [954] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(152), 1,
      anon_sym_COLON,
    ACTIONS(154), 1,
      anon_sym_extends,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    STATE(78), 1,
      sym_model_body,
    STATE(99), 1,
      sym_extends_clause,
  [973] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(160), 1,
      anon_sym_COLON,
    ACTIONS(158), 4,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_RBRACE,
      sym_identifier,
  [986] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 5,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_LBRACE,
      sym_identifier,
  [997] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 5,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_RBRACE,
      sym_identifier,
  [1008] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(166), 1,
      sym_identifier,
    ACTIONS(168), 1,
      anon_sym_RBRACE,
    STATE(83), 1,
      sym_object_entry,
    STATE(100), 1,
      sym_string_literal,
  [1027] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(166), 1,
      sym_identifier,
    ACTIONS(170), 1,
      anon_sym_RBRACE,
    STATE(93), 1,
      sym_object_entry,
    STATE(100), 1,
      sym_string_literal,
  [1046] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(172), 5,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_LBRACE,
      sym_identifier,
  [1057] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_LBRACE,
    STATE(82), 1,
      sym_plugin_block,
    ACTIONS(174), 3,
      ts_builtin_sym_end,
      anon_sym_DASH,
      sym_identifier,
  [1072] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(166), 1,
      sym_identifier,
    ACTIONS(176), 1,
      anon_sym_RBRACE,
    STATE(93), 1,
      sym_object_entry,
    STATE(100), 1,
      sym_string_literal,
  [1091] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 5,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_RBRACE,
      sym_identifier,
  [1102] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(180), 4,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_RBRACE,
      sym_identifier,
  [1112] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 4,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      sym_identifier,
  [1122] = 4,
    ACTIONS(184), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_DQUOTE,
    STATE(62), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(188), 2,
      sym_string_content,
      sym_escape_sequence,
  [1136] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_AT,
    ACTIONS(191), 1,
      anon_sym_RBRACE,
    STATE(69), 2,
      sym_plugin_config,
      aux_sym_plugin_block_repeat1,
  [1150] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(193), 4,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      sym_identifier,
  [1160] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 4,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_RBRACE,
      sym_identifier,
  [1170] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_git_COLON,
    ACTIONS(199), 1,
      sym_plugin_path,
    STATE(49), 1,
      sym_plugin_source,
    STATE(52), 1,
      sym_git_reference,
  [1186] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 4,
      ts_builtin_sym_end,
      anon_sym_AT,
      anon_sym_DASH,
      sym_identifier,
  [1196] = 4,
    ACTIONS(184), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_DQUOTE,
    STATE(62), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(205), 2,
      sym_string_content,
      sym_escape_sequence,
  [1210] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(207), 1,
      anon_sym_AT,
    ACTIONS(210), 1,
      anon_sym_RBRACE,
    STATE(69), 2,
      sym_plugin_config,
      aux_sym_plugin_block_repeat1,
  [1224] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      anon_sym_AT,
    ACTIONS(212), 1,
      anon_sym_RBRACE,
    STATE(63), 2,
      sym_plugin_config,
      aux_sym_plugin_block_repeat1,
  [1238] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 4,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_RBRACE,
      sym_identifier,
  [1248] = 4,
    ACTIONS(184), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_DQUOTE,
    STATE(68), 1,
      aux_sym_string_literal_repeat1,
    ACTIONS(218), 2,
      sym_string_content,
      sym_escape_sequence,
  [1262] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(166), 1,
      sym_identifier,
    STATE(93), 1,
      sym_object_entry,
    STATE(100), 1,
      sym_string_literal,
  [1278] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 4,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_RBRACE,
      sym_identifier,
  [1288] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 4,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_RBRACE,
      sym_identifier,
  [1298] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 4,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_RBRACE,
      sym_identifier,
  [1308] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 4,
      anon_sym_AT,
      anon_sym_DASH,
      anon_sym_RBRACE,
      sym_identifier,
  [1318] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 3,
      ts_builtin_sym_end,
      anon_sym_DASH,
      sym_identifier,
  [1327] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 3,
      ts_builtin_sym_end,
      anon_sym_DASH,
      sym_identifier,
  [1336] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_COMMA,
    ACTIONS(234), 1,
      anon_sym_LBRACE,
    STATE(88), 1,
      aux_sym_extends_clause_repeat1,
  [1349] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_COMMA,
    ACTIONS(239), 1,
      anon_sym_RBRACE,
    STATE(81), 1,
      aux_sym_object_literal_repeat1,
  [1362] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 3,
      ts_builtin_sym_end,
      anon_sym_DASH,
      sym_identifier,
  [1371] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(243), 1,
      anon_sym_COMMA,
    ACTIONS(245), 1,
      anon_sym_RBRACE,
    STATE(90), 1,
      aux_sym_object_literal_repeat1,
  [1384] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 3,
      ts_builtin_sym_end,
      anon_sym_DASH,
      sym_identifier,
  [1393] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(249), 1,
      anon_sym_COMMA,
    ACTIONS(251), 1,
      anon_sym_RBRACK,
    STATE(87), 1,
      aux_sym_array_literal_repeat1,
  [1406] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(253), 1,
      anon_sym_COMMA,
    ACTIONS(256), 1,
      anon_sym_RBRACK,
    STATE(86), 1,
      aux_sym_array_literal_repeat1,
  [1419] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(27), 1,
      anon_sym_RBRACK,
    ACTIONS(258), 1,
      anon_sym_COMMA,
    STATE(86), 1,
      aux_sym_array_literal_repeat1,
  [1432] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_COMMA,
    ACTIONS(260), 1,
      anon_sym_LBRACE,
    STATE(89), 1,
      aux_sym_extends_clause_repeat1,
  [1445] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_COMMA,
    ACTIONS(265), 1,
      anon_sym_LBRACE,
    STATE(89), 1,
      aux_sym_extends_clause_repeat1,
  [1458] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      anon_sym_RBRACE,
    ACTIONS(267), 1,
      anon_sym_COMMA,
    STATE(81), 1,
      aux_sym_object_literal_repeat1,
  [1471] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(269), 3,
      ts_builtin_sym_end,
      anon_sym_DASH,
      sym_identifier,
  [1480] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(271), 3,
      ts_builtin_sym_end,
      anon_sym_DASH,
      sym_identifier,
  [1489] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(239), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1497] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(273), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1505] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      anon_sym_PIPE,
    STATE(17), 1,
      aux_sym_union_type_repeat1,
  [1515] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1523] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_LBRACE,
    STATE(65), 1,
      sym_object_literal,
  [1533] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(275), 2,
      anon_sym_COMMA,
      anon_sym_LBRACE,
  [1541] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    STATE(84), 1,
      sym_model_body,
  [1551] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(277), 1,
      anon_sym_COLON,
  [1558] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(279), 1,
      sym_path,
  [1565] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(281), 1,
      sym_identifier,
  [1572] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      sym_identifier,
  [1579] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(285), 1,
      ts_builtin_sym_end,
  [1586] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      sym_identifier,
  [1593] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(289), 1,
      sym_identifier,
  [1600] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      sym_identifier,
  [1607] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(293), 1,
      anon_sym_RBRACK,
  [1614] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(295), 1,
      sym_identifier,
  [1621] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(297), 1,
      sym_git_url,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 30,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 90,
  [SMALL_STATE(6)] = 117,
  [SMALL_STATE(7)] = 144,
  [SMALL_STATE(8)] = 171,
  [SMALL_STATE(9)] = 188,
  [SMALL_STATE(10)] = 215,
  [SMALL_STATE(11)] = 242,
  [SMALL_STATE(12)] = 269,
  [SMALL_STATE(13)] = 286,
  [SMALL_STATE(14)] = 313,
  [SMALL_STATE(15)] = 337,
  [SMALL_STATE(16)] = 361,
  [SMALL_STATE(17)] = 385,
  [SMALL_STATE(18)] = 404,
  [SMALL_STATE(19)] = 421,
  [SMALL_STATE(20)] = 440,
  [SMALL_STATE(21)] = 455,
  [SMALL_STATE(22)] = 474,
  [SMALL_STATE(23)] = 490,
  [SMALL_STATE(24)] = 510,
  [SMALL_STATE(25)] = 530,
  [SMALL_STATE(26)] = 552,
  [SMALL_STATE(27)] = 566,
  [SMALL_STATE(28)] = 590,
  [SMALL_STATE(29)] = 614,
  [SMALL_STATE(30)] = 628,
  [SMALL_STATE(31)] = 642,
  [SMALL_STATE(32)] = 656,
  [SMALL_STATE(33)] = 680,
  [SMALL_STATE(34)] = 700,
  [SMALL_STATE(35)] = 714,
  [SMALL_STATE(36)] = 728,
  [SMALL_STATE(37)] = 748,
  [SMALL_STATE(38)] = 769,
  [SMALL_STATE(39)] = 782,
  [SMALL_STATE(40)] = 801,
  [SMALL_STATE(41)] = 814,
  [SMALL_STATE(42)] = 833,
  [SMALL_STATE(43)] = 846,
  [SMALL_STATE(44)] = 859,
  [SMALL_STATE(45)] = 872,
  [SMALL_STATE(46)] = 888,
  [SMALL_STATE(47)] = 904,
  [SMALL_STATE(48)] = 922,
  [SMALL_STATE(49)] = 938,
  [SMALL_STATE(50)] = 954,
  [SMALL_STATE(51)] = 973,
  [SMALL_STATE(52)] = 986,
  [SMALL_STATE(53)] = 997,
  [SMALL_STATE(54)] = 1008,
  [SMALL_STATE(55)] = 1027,
  [SMALL_STATE(56)] = 1046,
  [SMALL_STATE(57)] = 1057,
  [SMALL_STATE(58)] = 1072,
  [SMALL_STATE(59)] = 1091,
  [SMALL_STATE(60)] = 1102,
  [SMALL_STATE(61)] = 1112,
  [SMALL_STATE(62)] = 1122,
  [SMALL_STATE(63)] = 1136,
  [SMALL_STATE(64)] = 1150,
  [SMALL_STATE(65)] = 1160,
  [SMALL_STATE(66)] = 1170,
  [SMALL_STATE(67)] = 1186,
  [SMALL_STATE(68)] = 1196,
  [SMALL_STATE(69)] = 1210,
  [SMALL_STATE(70)] = 1224,
  [SMALL_STATE(71)] = 1238,
  [SMALL_STATE(72)] = 1248,
  [SMALL_STATE(73)] = 1262,
  [SMALL_STATE(74)] = 1278,
  [SMALL_STATE(75)] = 1288,
  [SMALL_STATE(76)] = 1298,
  [SMALL_STATE(77)] = 1308,
  [SMALL_STATE(78)] = 1318,
  [SMALL_STATE(79)] = 1327,
  [SMALL_STATE(80)] = 1336,
  [SMALL_STATE(81)] = 1349,
  [SMALL_STATE(82)] = 1362,
  [SMALL_STATE(83)] = 1371,
  [SMALL_STATE(84)] = 1384,
  [SMALL_STATE(85)] = 1393,
  [SMALL_STATE(86)] = 1406,
  [SMALL_STATE(87)] = 1419,
  [SMALL_STATE(88)] = 1432,
  [SMALL_STATE(89)] = 1445,
  [SMALL_STATE(90)] = 1458,
  [SMALL_STATE(91)] = 1471,
  [SMALL_STATE(92)] = 1480,
  [SMALL_STATE(93)] = 1489,
  [SMALL_STATE(94)] = 1497,
  [SMALL_STATE(95)] = 1505,
  [SMALL_STATE(96)] = 1515,
  [SMALL_STATE(97)] = 1523,
  [SMALL_STATE(98)] = 1533,
  [SMALL_STATE(99)] = 1541,
  [SMALL_STATE(100)] = 1551,
  [SMALL_STATE(101)] = 1558,
  [SMALL_STATE(102)] = 1565,
  [SMALL_STATE(103)] = 1572,
  [SMALL_STATE(104)] = 1579,
  [SMALL_STATE(105)] = 1586,
  [SMALL_STATE(106)] = 1593,
  [SMALL_STATE(107)] = 1600,
  [SMALL_STATE(108)] = 1607,
  [SMALL_STATE(109)] = 1614,
  [SMALL_STATE(110)] = 1621,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_model_body_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_model_body_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_model_body_repeat1, 2, 0, 0), SHIFT_REPEAT(105),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_model_body_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_union_type, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__union_member, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_union_type_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_union_type_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_identifier, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_expression, 1, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 1, 0, 7),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_literal, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_literal, 3, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_literal, 5, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_literal, 4, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [111] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(50),
  [114] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(109),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plugin_import, 2, 0, 1),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_plugin_import, 2, 0, 1),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 4, 0, 18),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 3, 0, 5),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 4, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 5, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 5, 0, 19),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [145] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 6, 0, 22),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plugin_import, 4, 0, 9),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 2, 0, 12),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plugin_source, 1, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plugin_block, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_git_reference, 2, 0, 14),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_alias, 3, 0, 5),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plugin_block, 3, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 5, 0, 20),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plugin_import, 5, 0, 15),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [188] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extends_directive, 2, 0, 2),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plugin_config, 3, 0, 4),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plugin_import, 3, 0, 4),
  [203] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [207] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_plugin_block_repeat1, 2, 0, 0), SHIFT_REPEAT(102),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_plugin_block_repeat1, 2, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 4, 0, 10),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_removal, 2, 0, 1),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 6, 0, 21),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_override, 2, 0, 13),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field_definition, 7, 0, 23),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_model_definition, 2, 0, 3),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_model_body, 2, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extends_clause, 2, 0, 6),
  [236] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_literal_repeat1, 2, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_alias, 4, 0, 10),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_model_definition, 3, 0, 8),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [253] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2, 0, 0),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extends_clause, 3, 0, 11),
  [262] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_extends_clause_repeat1, 2, 0, 16), SHIFT_REPEAT(107),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_extends_clause_repeat1, 2, 0, 16),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_model_removal, 2, 0, 1),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_model_body, 3, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_entry, 3, 0, 17),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_extends_clause_repeat1, 2, 0, 6),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [279] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [285] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [297] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_cdm(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "cdm",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
