mod validate;
mod diagnostics;
mod symbol_table;
mod plugin_runner;
mod file_resolver;
mod grammar_parser;
mod resolved_schema;
mod plugin_validation;
mod plugin_resolver;
mod template_resolver;
mod template_validation;
mod build;
mod migrate;
mod plugin_new;
mod format;
mod registry;
mod template_registry;
mod plugin_cache;
mod version_resolver;
mod git_plugin;
mod plugin_commands;
mod template_commands;
mod self_update;
mod update_command;
mod uninstall;
mod capabilities;
mod project_scanner;
mod dependency_graph;
mod descendant_ids;
pub mod lsp;

pub use diagnostics::{Diagnostic, Severity, node_span};
pub use cdm_utils::{Position, Span};
pub use symbol_table::{Ancestor, SymbolTable, Definition, DefinitionKind, FieldInfo, ImportedNamespace, QualifiedName, field_exists_in_parents, is_builtin_type, is_reserved_type_name, is_type_defined, resolve_definition, is_qualified_type_defined, is_type_reference_defined, resolve_qualified_definition};
pub use validate::{validate, validate_tree, validate_tree_with_options, validate_tree_cache_only, validate_with_templates, ValidationResult};
pub use plugin_runner::PluginRunner;
pub use file_resolver::{FileResolver, LoadedFile, LoadedFileTree};
pub use grammar_parser::GrammarParser;
pub use resolved_schema::{ResolvedSchema, ResolvedTypeAlias, ResolvedModel, ResolvedField, build_resolved_schema, build_cdm_schema_for_plugin, convert_type_expression, find_references_in_resolved, ParsedType, PrimitiveType};
pub use plugin_validation::{PluginImport, PluginSource, extract_plugin_imports, extract_structured_plugin_configs, ExtractedPluginConfigs, parse_object_literal_to_json};
pub use template_resolver::{TemplateImport, TemplateExtends, TemplateSource, TemplateManifest, LoadedTemplate, extract_template_imports, extract_template_extends, resolve_template, resolve_template_extends, get_entity_id_source, get_import_entity_id_source, get_extends_entity_id_source};
pub use template_validation::{validate_template_imports, validate_qualified_type_reference, extract_templates_from_source, check_unused_namespaces, collect_used_namespaces};
pub use build::build;
pub use migrate::migrate;
pub use plugin_new::plugin_new;
pub use format::{format_file, format_files, FormatOptions, FormatResult, IdAssignment, EntityType};
pub use project_scanner::ProjectScanner;
pub use dependency_graph::DependencyGraph;
pub use descendant_ids::{collect_descendant_ids, DescendantIds};
pub use plugin_commands::{list_plugins, plugin_info, cache_plugin_cmd, clear_cache_cmd};
pub use template_commands::{list_templates, template_info, cache_template_cmd, clear_template_cache_cmd};
pub use update_command::{UpdateCommands, update_latest, handle_update_subcommand};
pub use uninstall::uninstall;
pub use capabilities::{capabilities, CapabilitiesResult, PluginCapability};

// Re-export for testing
pub use registry::get_cache_path;
pub use template_registry::{TemplateRegistry, RegistryTemplate, RegistryTemplateVersion, load_template_registry, lookup_template, get_template_version};