mod validate;
mod diagnostics;
mod symbol_table;
mod plugin_runner;
mod file_resolver;
mod grammar_parser;
mod resolved_schema;
mod plugin_validation;
mod plugin_resolver;
mod build;
mod migrate;
mod plugin_new;
mod format;
mod registry;
mod plugin_cache;
mod version_resolver;
mod git_plugin;
mod plugin_commands;

pub use diagnostics::{Diagnostic, Severity};
pub use cdm_utils::{Position, Span};
pub use symbol_table::{Ancestor,SymbolTable, Definition, DefinitionKind, FieldInfo, field_exists_in_parents, is_builtin_type, is_type_defined, resolve_definition};
pub use validate::{validate, validate_tree, validate_tree_with_options, ValidationResult};
pub use plugin_runner::PluginRunner;
pub use file_resolver::{FileResolver, LoadedFile, LoadedFileTree};
pub use grammar_parser::GrammarParser;
pub use resolved_schema::{ResolvedSchema, ResolvedTypeAlias, ResolvedModel, ResolvedField, build_resolved_schema, build_cdm_schema_for_plugin, convert_type_expression, find_references_in_resolved, ParsedType, PrimitiveType};
pub use plugin_validation::{PluginImport, PluginSource, extract_plugin_imports, extract_structured_plugin_configs, ExtractedPluginConfigs};
pub use build::build;
pub use migrate::migrate;
pub use plugin_new::plugin_new;
pub use format::{format_file, format_files, FormatOptions, FormatResult, IdAssignment, EntityType};
pub use plugin_commands::{list_plugins, plugin_info, cache_plugin_cmd, clear_cache_cmd};